services:
  pgsql:
    image: postgres:latest
    container_name: pgsql
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - pgsql-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT}
    depends_on:
      - pgsql
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev

volumes:
  pgsql-data:
