CREATE TABLE SYS_USR(
    SYS_ID UUID PRIMARY KEY,
    SYS_NAME VARCHAR(30) NOT NULL,
    SYS_EMAIL VARCHAR(30) NOT NULL,
    SYS_PASSWORD VARCHAR(100) NOT NULL,
    SYS_ROLE VARCHAR(5) NOT NULL,
    SYS_SALT VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SB1_CLIENT(
    SB1_ID UUID PRIMARY KEY,
    SB1_ID_CLIENT UUID NOT NULL,
    SB1_NAME VARCHAR(30) NOT NULL,
    SB1_EMAIL VARCHAR(30) NOT NULL,
    SB1_PHONE VARCHAR(9) NOT NULL,
    SB1_SITUATION VARCHAR(2) NOT NULL,
    SB1_EVIDENCE VARCHAR(30) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sb1_client_user FOREIGN KEY (SB1_ID_CLIENT) REFERENCES SYS_USR(SYS_ID)
);